version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes: 
            - ./nginx:/etc/nginx/conf.d/
            - ./app:/app
    
    php:
        build: 
            context: .
            dockerfile: PHP_CUSTOM.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'testing'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "1025:1025"
            - "8025:8025"
volumes:
    mysqldata: {}